version: '3.9'
services:
  auth-db:
    container_name: localdb
    image: 'postgres:15.2-alpine'
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - './postgresData:/var/lib/postgresql/data'

volumes:
  postgresData:
